/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bl.Account;
import bl.AccountUser;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author martin
 */
public class AccountGUI extends javax.swing.JFrame {

	private Account sharedAccount;
	private AccountListModel acm;

	/**
	 * Creates new form AccountGUI
	 */
	public AccountGUI() {
		initComponents();
		this.acm = new AccountListModel();
		this.account_list.setModel(this.acm);
		this.sharedAccount = new Account(current_balance);
	}

	private void refreshReferences(List<AccountUser> users) {
		for (AccountUser u : users) {
			u.setSharedAccount(sharedAccount);
			u.setOutput(transfer_output);
		}
	}

	private void startWorkers(List<AccountUser> users) throws InterruptedException {
		for (AccountUser u : users) {
			Thread t = new Thread(u, u.getName());
			t.setPriority(Thread.NORM_PRIORITY + 1);
			t.start();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                user_account_menu = new javax.swing.JPopupMenu();
                add_user = new javax.swing.JMenuItem();
                start_activity = new javax.swing.JMenuItem();
                bank_account_menu = new javax.swing.JPopupMenu();
                create_new_acc = new javax.swing.JMenuItem();
                jScrollPane1 = new javax.swing.JScrollPane();
                account_list = new javax.swing.JList<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                transfer_output = new javax.swing.JTextArea();
                current_balance = new javax.swing.JLabel();

                add_user.setText("Add new User");
                add_user.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                add_userActionPerformed(evt);
                        }
                });
                user_account_menu.add(add_user);

                start_activity.setText("Start Transfers");
                start_activity.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                start_activityActionPerformed(evt);
                        }
                });
                user_account_menu.add(start_activity);

                create_new_acc.setText("Create new Account");
                create_new_acc.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                create_new_accActionPerformed(evt);
                        }
                });
                bank_account_menu.add(create_new_acc);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                account_list.setBorder(javax.swing.BorderFactory.createTitledBorder("Accounts"));
                account_list.setComponentPopupMenu(user_account_menu);
                jScrollPane1.setViewportView(account_list);

                getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_START);

                transfer_output.setColumns(20);
                transfer_output.setRows(5);
                transfer_output.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
                transfer_output.setComponentPopupMenu(bank_account_menu);
                jScrollPane2.setViewportView(transfer_output);

                getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

                current_balance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                current_balance.setText("50€");
                current_balance.setBorder(javax.swing.BorderFactory.createTitledBorder("Balance"));
                getContentPane().add(current_balance, java.awt.BorderLayout.PAGE_END);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
		String res = JOptionPane.showInputDialog("Add user...");
		AccountUser au = new AccountUser(res, this.sharedAccount, this.transfer_output);
		this.acm.addUser(au);
        }//GEN-LAST:event_add_userActionPerformed

        private void start_activityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_activityActionPerformed
		List<AccountUser> selectedUsers = account_list.getSelectedValuesList(); //get selected accounts from the gui
		this.refreshReferences(selectedUsers); //make sure the workers have the proper references...
		try {
			this.startWorkers(selectedUsers); //... and spin them up!
		} catch (InterruptedException ex) {
		}
        }//GEN-LAST:event_start_activityActionPerformed

        private void create_new_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_new_accActionPerformed
		this.sharedAccount = new Account(current_balance);
		this.transfer_output.setText("");
        }//GEN-LAST:event_create_new_accActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AccountGUI().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList<AccountUser> account_list;
        private javax.swing.JMenuItem add_user;
        private javax.swing.JPopupMenu bank_account_menu;
        private javax.swing.JMenuItem create_new_acc;
        private javax.swing.JLabel current_balance;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JMenuItem start_activity;
        private javax.swing.JTextArea transfer_output;
        private javax.swing.JPopupMenu user_account_menu;
        // End of variables declaration//GEN-END:variables
}
